In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/PJM_Load_hourly.csv")

df["Datetime"] = pd.to_datetime(df["Datetime"])

df = df.sort_values("Datetime")

df = df.set_index("Datetime")

print(df.shape)

df.head()

(32896, 1)

                     PJM_Load_MW
Datetime
1998-04-01 01:00:00      22259.0
1998-04-01 02:00:00      21244.0
1998-04-01 03:00:00      20651.0
1998-04-01 04:00:00      20421.0
1998-04-01 05:00:00      20713.0

In [2]:
df.shape

(32896, 1)

In [3]:
for lag in range(1, 25):
    df[f"lag_{lag}"] = df["PJM_Load_MW"].shift(lag)

df.head()

,PJM_Load_MW,lag_1,lag_2,lag_3,lag_4,lag_5,lag_6,lag_7,lag_8,lag_9,...,lag_15,lag_16,lag_17,lag_18,lag_19,lag_20,lag_21,lag_22,lag_23,lag_24
Datetime,,,,,,,,,,,,,,,,,,,,,
1998-04-01 01:00:00,22259.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-04-01 02:00:00,21244.0,22259.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-04-01 03:00:00,20651.0,21244.0,22259.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-04-01 04:00:00,20421.0,20651.0,21244.0,22259.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-04-01 05:00:00,20713.0,20421.0,20651.0,21244.0,22259.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index(['PJM_Load_MW', 'lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_5', 'lag_6',
       'lag_7', 'lag_8', 'lag_9', 'lag_10', 'lag_11', 'lag_12', 'lag_13',
       'lag_14', 'lag_15', 'lag_16', 'lag_17', 'lag_18', 'lag_19', 'lag_20',
       'lag_21', 'lag_22', 'lag_23', 'lag_24'],
      dtype='str')

In [5]:
len(df.columns)

25

In [6]:
df["rolling_mean_24"] = df["PJM_Load_MW"].rolling(window=24).mean()

df["rolling_std_24"] = df["PJM_Load_MW"].rolling(window=24).std()

df["rolling_min_24"] = df["PJM_Load_MW"].rolling(window=24).min()

df["rolling_max_24"] = df["PJM_Load_MW"].rolling(window=24).max()

In [7]:
df.head()

,PJM_Load_MW,lag_1,lag_2,lag_3,lag_4,lag_5,lag_6,lag_7,lag_8,lag_9,...,lag_19,lag_20,lag_21,lag_22,lag_23,lag_24,rolling_mean_24,rolling_std_24,rolling_min_24,rolling_max_24
Datetime,,,,,,,,,,,,,,,,,,,,,
1998-04-01 01:00:00,22259.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-04-01 02:00:00,21244.0,22259.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-04-01 03:00:00,20651.0,21244.0,22259.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-04-01 04:00:00,20421.0,20651.0,21244.0,22259.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-04-01 05:00:00,20713.0,20421.0,20651.0,21244.0,22259.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
print("Before:", df.shape)

df = df.dropna()

print("After:", df.shape)

Before: (32896, 29)
After: (32872, 29)

In [10]:
df.isnull().sum().sum()

np.int64(0)

In [11]:
print(df.shape)
print(df.isnull().sum().sum())

(32872, 29)
0