In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/raw/PJM_Load_hourly.csv")

df["Datetime"] = pd.to_datetime(df["Datetime"])

df = df.sort_values("Datetime")

df = df.set_index("Datetime")

df.head()

                     PJM_Load_MW
Datetime
1998-04-01 01:00:00      22259.0
1998-04-01 02:00:00      21244.0
1998-04-01 03:00:00      20651.0
1998-04-01 04:00:00      20421.0
1998-04-01 05:00:00      20713.0

In [3]:
df["time_idx"] = np.arange(len(df))

df[["PJM_Load_MW", "time_idx"]].head()

                     PJM_Load_MW  time_idx
Datetime
1998-04-01 01:00:00      22259.0         0
1998-04-01 02:00:00      21244.0         1
1998-04-01 03:00:00      20651.0         2
1998-04-01 04:00:00      20421.0         3
1998-04-01 05:00:00      20713.0         4

In [4]:
X_trend = df[["time_idx"]]

y_trend = df["PJM_Load_MW"]

trend_model = LinearRegression()

trend_model.fit(X_trend, y_trend)

df["trend_prediction"] = trend_model.predict(X_trend)

df.head()

                     PJM_Load_MW  time_idx  trend_prediction
Datetime
1998-04-01 01:00:00      22259.0         0      28926.935424
1998-04-01 02:00:00      21244.0         1      28926.986464
1998-04-01 03:00:00      20651.0         2      28927.037505
1998-04-01 04:00:00      20421.0         3      28927.088546
1998-04-01 05:00:00      20713.0         4      28927.139586

In [5]:
df["residual"] = (
    df["PJM_Load_MW"]
    - df["trend_prediction"]
)

df[["PJM_Load_MW",
    "trend_prediction",
    "residual"]].head()

                     PJM_Load_MW  trend_prediction     residual
Datetime
1998-04-01 01:00:00      22259.0      28926.935424 -6667.935424
1998-04-01 02:00:00      21244.0      28926.986464 -7682.986464
1998-04-01 03:00:00      20651.0      28927.037505 -8276.037505
1998-04-01 04:00:00      20421.0      28927.088546 -8506.088546
1998-04-01 05:00:00      20713.0      28927.139586 -8214.139586